# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
# 
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = "check"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy"]
need_stdout = false

[jobs.clippy-all]
command = ["cargo", "clippy", "--all-targets"]
need_stdout = false

[jobs.web]
command = [
    "cargo", "run", "--bin=balancer-sdai-eure-incident-app",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
watch = ["crates/balancer-sdai-eure-incident-app/templates", "crates/balancer-sdai-eure-incident-app/assets"]

[jobs.css]
command = [
    "tailwindcss", "-i", "crates/balancer-sdai-eure-incident-app/assets/style.css", "-o", "crates/balancer-sdai-eure-incident-app/assets/style-out.css",
]
need_stdout = true
allow_warnings = true
watch = ["crates/balancer-sdai-eure-incident-app/templates", "crates/balancer-sdai-eure-incident-app/assets"]

[keybindings]
# alt-m = "job:my-job"
c = "job:clippy-all" # comment this to have 'c' run clippy on only the default target
