[workspace]
resolver = "2"
members = ["crates/balancer-sdai-eure-incident-app", "crates/balancer-sdai-eure-incident-data-generation"]

[workspace.dependencies]
tokio = { version = "1.44.2", features = ["full"] }
eyre = "0.6.12"
clap = { version = "4.5.37", features = ["derive"] }
log = "0.4.27"
env_logger = "0.11.8"
csv = "1.3.1"
serde = "1.0.219"
serde_json = "1.0.140"
chrono = "0.4.41"